[phases.setup]
nixPkgs = ["busybox", "nodejs", "nodePackages.pm2"]
aptPkgs = ["ca-certificates", "curl"]

[phases.install]
cmds = [
    "curl -fsSL https://bun.sh/install | bash",
    "export BUN_INSTALL=\"$HOME/.bun\"",
    "export PATH=\"$BUN_INSTALL/bin:$PATH\"",
    "bun install"
]

[phases.build]
cmds = [
    "export BUN_INSTALL=\"$HOME/.bun\"", 
    "export PATH=\"$BUN_INSTALL/bin:$PATH\"",
    "bun run build"
]

[start]
cmd = '/assets/start.sh'

[staticAssets]
"start.sh" = '''
#!/bin/bash
# Export Bun path directly (don't rely on bashrc sourcing)
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Log Bun version for debugging
echo "Bun version: $(bun --version)"

# Run the application based on environment
if [ "$NODE_ENV" = "production" ]; then
    # Use PM2 in production
    echo "Starting in production mode with PM2..."
    pm2-runtime start pm2.config.js --env production
else
    # Use development mode
    echo "Starting in development mode..."
    bun run dev
fi
'''

"pm2.config.js" = '''
module.exports = {
  apps: [
    {
      name: 'next-app',
      script: './node_modules/.bin/next',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3000
      }
    }
  ]
};
'''