[phases.setup]
nixPkgs = ["busybox", "nodejs", "nodePackages.pm2"]
aptPkgs = ["ca-certificates"]

[phases.install]
cmds = [
    "curl -fsSL https://bun.sh/install | bash",
    "export BUN_INSTALL=\"$HOME/.bun\"",
    "export PATH=\"$BUN_INSTALL/bin:$PATH\"",
    "bun install"
]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = '/assets/start.sh'

[staticAssets]
"start.sh" = '''
#!/bin/bash
# Start application with PM2
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

if [ "$NODE_ENV" = "production" ]; then
    # Production mode - use the built application
    pm2-runtime start pm2.config.js --env production
else
    # Development mode
    bun run dev
fi
'''

"pm2.config.js" = '''
module.exports = {
  apps: [
    {
      name: 'next-app',
      script: 'bun',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3000
      }
    }
  ]
};
'''
