[phases.setup]
nixPkgs = ["busybox", "nodejs", "nodePackages.pm2"]
aptPkgs = ["ca-certificates", "curl", "wget"]

[phases.install]
cmds = ["bash ./install.sh"]

# Skip the build phase since we already built in the install script
[phases.build]
cmds = ["echo 'Build already completed in install phase'"]

[start]
cmd = 'bash -c "export BUN_INSTALL=\"$HOME/.bun\" && export PATH=\"$BUN_INSTALL/bin:$PATH\" && if [ \"$NODE_ENV\" = \"production\" ]; then pm2-runtime start pm2.config.js --env production; else $HOME/.bun/bin/bun run dev; fi"'

[staticAssets]
"pm2.config.js" = '''
module.exports = {
  apps: [
    {
      name: 'next-app',
      script: './node_modules/.bin/next',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3000,
        NODE_OPTIONS: '--max-old-space-size=512' // Adjust buffer size
      }
    }
  ]
};
'''